name: Deploy to AWS using Copilot

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: af-south-1
  COPILOT_ENVIRONMENT: prod
  COPILOT_SERVICE: api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up docker
        uses: docker/setup-buildx-action@v1

      - name: Check if AWS CLI is installed
        id: check-aws-cli
        run: |
          if ! command -v aws &> /dev/null
          then
              echo "AWS CLI could not be found, installing..."
              echo "install" >> $GITHUB_ENV
          else
              echo "AWS CLI is installed, updating..."
              echo "update" >> $GITHUB_ENV
          fi

      - name: Install or update AWS CLI
        run: |
          if [ "$GITHUB_ENV" == "install" ]; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
          elif [ "$GITHUB_ENV" == "update" ]; then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install Copilot CLI
        run: |
          curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot
          sudo mv copilot /usr/local/bin/copilot

      - name: Deploy to AWS
        run: copilot svc deploy --name ${{ env.COPILOT_SERVICE }} --env ${{ env.COPILOT_ENVIRONMENT }}
