name: Deploy to AWS using Copilot

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/workflows/aws.yml'

env:
  AWS_REGION: af-south-1
  COPILOT_ENVIRONMENT: prod
  COPILOT_SERVICE: api
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

      - name: Check if AWS CLI is installed
        id: check-aws-cli
        run: |
          if command -v aws &> /dev/null
          then
            echo "aws_installed=true" >> $GITHUB_ENV
          else
            echo "aws_installed=false" >> $GITHUB_ENV
          fi

      - name: Install AWS CLI if not installed
        if: env.aws_installed == 'false'
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install Copilot CLI
        run: |
          curl -Lo /tmp/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x /tmp/copilot
          sudo mv /tmp/copilot /usr/local/bin/copilot

      - name: Deploy to AWS
        run: copilot svc deploy --name ${{ env.COPILOT_SERVICE }} --env ${{ env.COPILOT_ENVIRONMENT }}
